# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cwd
version:      2.14
version_from: Cwd.pm
installdirs:  perl
requires:
    Carp:                          0
    File::Path:                    0
    File::Spec:                    0
    Scalar::Util:                  0
    Test::More:                    0
    XSLoader:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
