--- #YAML:1.0
name: Cwd
version: 2.17
author:
  - Originally by the perl5-porters.
abstract: get pathname of current working directory
license: perl
requires:
  Carp: 0
  File::Spec: 0
  XSLoader: 0
build_requires:
  File::Path: 0
  Module::Build: 0.19
  Scalar::Util: 0
  Test::More: 0
provides:
  Cwd:
    file: Cwd.pm
    version: 2.17
generated_by: Module::Build version 0.23
