--- #YAML:1.0
name: Cwd
version: 2.18_01
author:
  - Maintained by Ken Williams <KWILLIAMS@cpan.org>
abstract: get pathname of current working directory
license: perl
requires:
  Carp: 0
  File::Spec: 0
  XSLoader: 0
build_requires:
  File::Path: 0
  Module::Build: 0.19
  Scalar::Util: 0
  Test::More: 0
provides:
  Cwd:
    file: Cwd.pm
    version: 2.18_01
generated_by: Module::Build version 0.25_01
